//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int ReceiptId { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> DateOfSubmit { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
