//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn_Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Fees = new HashSet<Fee>();
            this.Libraries = new HashSet<Library>();
        }
    
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Library> Libraries { get; set; }
    }
}
